utdallasiia/apps/resumebook/urls.py
from django.conf.urls import patterns, include, url
from utdallasiia.apps.resumebook.views import ResumeBookView, SubmitResume, DownloadResume

urlpatterns = patterns('',
    url(r'^$', ResumeBookView.as_view(), name='resume_book_view'),
    url(r'^submit/$', SubmitResume.as_view(), name='submit_resume'),
    url(r'^download/(?P<pk>\d+)/$', DownloadResume.as_view(), name='download_resume'),
)

utdallasiia/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic.simple import redirect_to
from django.views.generic.base import TemplateView

admin.autodiscover()

urlpatterns = patterns('',
    # Setup LinkedIn login/logout urls
    url(r'', include('social_auth.urls')),
    url(r'^login/$', TemplateView.as_view(template_name='login.html'), name='auth_login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='auth_logout'),
    
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    # Setup Paypal IPN
    url(settings.PAYPAL_IPN_URL, include('paypal.standard.ipn.urls')),
    
    # Django Blog Zinnia
    url(r'^blog/', include('zinnia.urls')),
    url(r'^comments/', include('django.contrib.comments.urls')),
    
    # Finally, load Django CMS urls
    url(r'^', include('cms.urls')),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.SMEDIA_URL, document_root=settings.SMEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

utdallasiia/apps/resumebook/models.py
import os
from uuid import uuid4
from django.contrib.auth.models import User
from django.db import models
from utdallasiia.libs.resumefilefield import ContentTypeRestrictedFileField
from utdallasiia.libs.smedia import smedia_storage

class Resume(models.Model):
    NONE_STATUS = 0
    PENDING_STATUS = 1
    ACCEPTED_STATUS = 2
    STATUS_CHOICES = (
        (NONE_STATUS, 'None'),
        (PENDING_STATUS, 'Pending'),
        (ACCEPTED_STATUS, 'Accepted'),
    )
    
    POSITION_CHOICES = (
        ('FT', 'Full-time'),
        ('IN', 'Intern'),
        ('NA', 'Not Looking'),
    )
    
    TRAVEL_CHOICES = (
        ('0', '0%'),
        ('25', '25%'),
        ('50', '50%'),
        ('75', '75%'),
        ('100', '100%'),
    )
    
    YES_OR_NO = (
        ('Y', 'Yes'),
        ('N', 'No'),
    )
    
    def get_file_path(instance, filename):
        ext = filename.split('.')[-1]
        try:
            base = instance.user.memberprofile.netid
        except:
            base = 'resume'
        filename = "%s.%s.%s" % (base, uuid4(), ext)
        return os.path.join('resumebook', filename)
    
    user = models.OneToOneField(User)
    last_modified = models.DateTimeField(auto_now=True)
    position = models.CharField(max_length=2, choices=POSITION_CHOICES)
    travel = models.CharField(max_length=3, choices=TRAVEL_CHOICES)
    relocate = models.CharField(max_length=1, choices=YES_OR_NO)
    ia_course = models.CharField(max_length=1, choices=YES_OR_NO)
    it_position = models.CharField(max_length=1, choices=YES_OR_NO, default='N')
    iia_membership = models.CharField(max_length=30, blank=True)
    isaca_membership = models.CharField(max_length=30, blank=True)
    acfe_membership = models.CharField(max_length=30, blank=True)
    resume = ContentTypeRestrictedFileField(
        upload_to=get_file_path,
        storage=smedia_storage,
        content_types=['application/pdf'],
        max_upload_size=1048576,
    )
    student_status = models.IntegerField(choices=STATUS_CHOICES, default=NONE_STATUS)
    access_status = models.IntegerField(choices=STATUS_CHOICES, default=NONE_STATUS)
    
    travel.verbose_name = 'Percentage of travel'
    relocate.verbose_name = 'Willing to relocate?'
    ia_course.verbose_name = 'Completed or enrolled in Internal Audit course?'
    it_position.verbose_name = 'IT position'
    iia_membership.verbose_name = 'IIA Membership Number'
    isaca_membership.verbose_name = 'ISACA Membership Number'
    acfe_membership.verbose_name = 'ACFE Membership Number'
    resume.help_text = 'Please submit as PDF. Only one page (1024kb file limit).'
    
    def __unicode__(self):
        return self.user.last_name

utdallasiia_site/members/models.py
from datetime import date

from django.conf import settings
from django.db import models
from django_localflavor_us.models import PhoneNumberField, USStateField

from model_utils import Choices


class DegreePlan(models.Model):
    degree = models.CharField(max_length=30)

    def __unicode__(self):
        return self.degree


class Member(models.Model):
    CLASSIFICATION = Choices(
        'Full-time',
        'Part-time',
    )

    YES_OR_NO = Choices(
        'Yes',
        'No',
    )

    GRAD_MONTH = Choices(
        'May',
        'August',
        'December'
    )

    GRAD_YEAR = [
        (k, k) for k in range(date.today().year - 4, date.today().year + 8)
    ]

    TSHIRT_SIZE = Choices(
        'Small',
        'Medium',
        'Large',
        'Extra Large',
        'Double Extra Large',
        'Triple Extra Large',
    )

    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    netid = models.CharField(max_length=30)
    phone_number = PhoneNumberField()
    street_address = models.CharField(max_length=95)
    city = models.CharField(max_length=35)
    state = USStateField()
    zip_code = models.CharField(max_length=10)
    tshirt_size = models.CharField(max_length=20, choices=TSHIRT_SIZE)
    degree_plans = models.ManyToManyField(DegreePlan)
    classification = models.CharField(max_length=20, choices=CLASSIFICATION)
    graduation_month = models.CharField(max_length=20, choices=GRAD_MONTH)
    graduation_year = models.IntegerField(choices=GRAD_YEAR)
    citizen_resident = models.CharField(max_length=20, choices=YES_OR_NO)

    # Setup verbose names/labels
    netid.verbose_name = 'Net ID'
    netid.help_text = 'e.g. jxd032000'
    phone_number.help_text = 'e.g. XXX-XXX-XXXX'
    tshirt_size.verbose_name = 't-shirt size'
    degree_plans.verbose_name = 'degree plan(s)'
    degree_plans.help_text = 'Choose all that apply'
    citizen_resident.verbose_name = ('Are you a U.S. Citizen or '
                                     'Permanent Resident?')

    def __unicode__(self):
        return self.user.last_name

utdallasiia_site/resumes/models.py
from os.path import join
from uuid import uuid4

from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models

from model_utils import Choices

from .filefields import ContentTypeRestrictedFileField
from .storage import smedia_storage


class Resume(models.Model):
    POSITION = Choices(
        'Full-time',
        'Intern',
        'Not Looking',
    )

    TRAVEL = Choices(
        '0%',
        '25%',
        '50%',
        '75%',
        '100%',
    )

    YES_OR_NO = Choices(
        'Yes',
        'No',
    )

    def get_file_path(instance, filename):
        ext = filename.split('.')[-1]
        try:
            base = instance.user.member.netid
        except:
            base = 'resume'
        filename = "%s.%s.%s" % (base, uuid4(), ext)
        return join('resumebook', filename)

    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    is_accepted = models.BooleanField(default=False)
    position = models.CharField(max_length=20, choices=POSITION)
    travel = models.CharField(max_length=20, choices=TRAVEL)
    relocate = models.CharField(max_length=20, choices=YES_OR_NO)
    ia_course = models.CharField(max_length=20, choices=YES_OR_NO)
    it_position = models.CharField(max_length=20, choices=YES_OR_NO,
                                   default=YES_OR_NO.No)
    iia_membership = models.CharField(max_length=30, blank=True)
    isaca_membership = models.CharField(max_length=30, blank=True)
    acfe_membership = models.CharField(max_length=30, blank=True)
    resume = ContentTypeRestrictedFileField(
        upload_to=get_file_path,
        storage=smedia_storage,
        content_types=['application/pdf'],
        max_upload_size=1048576,
    )

    travel.verbose_name = 'Percentage of travel'
    relocate.verbose_name = 'Willing to relocate?'
    ia_course.verbose_name = 'Completed or enrolled in Internal Audit course?'
    it_position.verbose_name = 'IT position'
    iia_membership.verbose_name = 'IIA Membership Number'
    isaca_membership.verbose_name = 'ISACA Membership Number'
    acfe_membership.verbose_name = 'ACFE Membership Number'
    resume.help_text = ('Please submit as PDF. '
                        'Only one page (1024kb file limit).')

    def __unicode__(self):
        return self.user.last_name

    def clean(self):
        if ((self.iia_membership ==
             self.isaca_membership ==
             self.acfe_membership == '')):
            raise ValidationError('You must belong to at least one of the '
                                  'three professional organizations.')

utdallasiia/apps/resumebook/forms.py
from django import forms
from utdallasiia.apps.resumebook.models import Resume

class ResumeForm(forms.ModelForm):
    class Meta:
        model = Resume
        exclude = (
            'user',
            'student_status',
            'access_status',
            'it_position',
        )
        widgets = {
            'resume': forms.widgets.FileInput,
        }
        
    def clean(self):
        cleaned_data = super(ResumeForm, self).clean()
        if cleaned_data['iia_membership'] == cleaned_data['isaca_membership'] == cleaned_data['acfe_membership'] == '':
            raise forms.ValidationError('You must belong to at least one of the three professional organizations.')
        else:
            return cleaned_data

utdallasiia/apps/resumebook/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.generic.detail import BaseDetailView
from django.views.generic.edit import UpdateView
from django.views.generic.list import ListView
from utdallasiia.apps.resumebook.forms import ResumeForm
from utdallasiia.apps.resumebook.models import Resume

class ResumeBookView(ListView):
    queryset = Resume.objects.filter(student_status=Resume.ACCEPTED_STATUS).order_by('user__last_name')
    raise_exception = False
    
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        has_permission = request.user.memberprofile.is_employer and request.user.resume.access_status == Resume.ACCEPTED_STATUS
        
        if not has_permission:  # If the user lacks the permission
            if self.raise_exception:  # *and* if an exception was desired
                raise PermissionDenied  # return a forbidden response.
            else:
                return render(request, 'resumebook/resume_access.html')
            
        return super(ResumeBookView, self).dispatch(request, *args, **kwargs)
        
class SubmitResume(UpdateView):
    form_class = ResumeForm
    success_url = reverse_lazy('dashboard_view')
    raise_exception = True
    
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        has_permission = request.user.memberprofile.is_paid
        
        if not has_permission:  # If the user lacks the permission
            if self.raise_exception:  # *and* if an exception was desired
                raise PermissionDenied  # return a forbidden response.
            
        return super(SubmitResume, self).dispatch(request, *args, **kwargs)
    
    def get_object(self):
        return self.request.user.resume
    
    def form_valid(self, form):
        resume = form.save(commit=False)
        resume.student_status = Resume.PENDING_STATUS
        resume.save()
        return super(SubmitResume, self).form_valid(form)

class DownloadResume(BaseDetailView):
    model = Resume
    raise_exception = True
    
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        has_permission = request.user.is_superuser or request.user.memberprofile.is_employer
        
        if not has_permission:  # If the user lacks the permission
            if self.raise_exception:  # *and* if an exception was desired
                raise PermissionDenied  # return a forbidden response.
            
        return super(DownloadResume, self).dispatch(request, *args, **kwargs)
    
    def get(self, request, *args, **kwargs):
        pk = self.kwargs.get(self.pk_url_kwarg, None)
        resume = Resume.objects.get(pk=pk)
        if resume.resume:
            response = HttpResponse(resume.resume, content_type='application/pdf')
            response['Content-Disposition'] = 'attachment; filename=%s%s.pdf' % (resume.user.first_name, resume.user.last_name)
            return response
        else:
            raise PermissionDenied

utdallasiia_site/resumes/views.py
# Create your views here.

utdallasiia/apps/resumebook/templates/resumebook/resume_access.html
{% extends "base.html" %}

{% block base_content %}
<div class="row">
	<div class="six columns centered">
		<div class="panel radius">
			<h3>For Employers Only</h3>
			<hr>
			<h5 class="subheader">You do not have permission to access the resume book at this time. If you are an employer, you may request access to view the resume book.</h5>
			<a class="secondary button" href="/">Back to Home</a>
			<a class="button" href="{% url dashboard_select 'employer' %}">Request access &raquo;</a>
			<hr>
		</div>
	</div>
</div>
{% endblock base_content %}

utdallasiia/apps/resumebook/templates/resumebook/resume_form.html
{% extends "base.html" %}

{% block base_content %}
<div class="row">
	<div class="twelve columns">
		<h3>Submit Resume</h3>
		<hr>
		<div class="eight columns end">
			<form enctype="multipart/form-data" method="post" action="" class="custom">
				{% csrf_token %}
				<div class="row">
					<div class="six columns {% if form.position.errors %}error{% endif %}">
						{{ form.position.label_tag }}
						{{ form.position }}
						{% for errors in form.position.errors %}
						<small>{{ errors|escape }}</small>
						{% endfor %}
						<p>
							{{ form.position.help_text }}
						</p>
					</div>
				</div>
				<div class="row">
					<div class="six columns {% if form.travel.errors %}error{% endif %}">
						{{ form.travel.label_tag }}
						{{ form.travel }}
						{% for errors in form.travel.errors %}
						<small>{{ errors|escape }}</small>
						{% endfor %}
						<p>
							{{ form.travel.help_text }}
						</p>
					</div>
				</div>
				<div class="row">
					<div class="six columns {% if form.relocate.errors %}error{% endif %}">
						{{ form.relocate.label_tag }}
						{{ form.relocate }}
						{% for errors in form.relocate.errors %}
						<small>{{ errors|escape }}</small>
						{% endfor %}
						<p>
							{{ form.relocate.help_text }}
						</p>
					</div>
				</div>
				<div class="row">
					<div class="six columns {% if form.ia_course.errors %}error{% endif %}">
						{{ form.ia_course.label_tag }}
						{{ form.ia_course }}
						{% for errors in form.ia_course.errors %}
						<small>{{ errors|escape }}</small>
						{% endfor %}
						<p>
							{{ form.ia_course.help_text }}
						</p>
					</div>
				</div>
				<fieldset>
					<legend>
						Professional organization membership:
					</legend>
					{% for errors in form.non_field_errors %}
					<small class="error">{{ errors|escape }}</small>
					{% endfor %}
					<p>
						As outlined in our bylaws, membership is required of at least one of the following professional organizations. Details and student membership pricing can be found on each of the organization's websites.
					</p>
					<div class="row">
						<div class="six columns {% if form.iia_membership.errors %}error{% endif %}">
							{{ form.iia_membership.label_tag }}
							{{ form.iia_membership }}
							{% for errors in form.iia_membership.errors %}
							<small>{{ errors|escape }}</small>
							{% endfor %}
							<p>
								<a href="https://theiia.org/" target="_blank">https://theiia.org/</a>
							</p>
						</div>
					</div>
					<div class="row">
						<div class="six columns {% if form.isaca_membership.errors %}error{% endif %}">
							{{ form.isaca_membership.label_tag }}
							{{ form.isaca_membership }}
							{% for errors in form.isaca_membership.errors %}
							<small>{{ errors|escape }}</small>
							{% endfor %}
							<p>
								<a href="https://www.isaca.org/" target="_blank">https://www.isaca.org/</a>
							</p>
						</div>
					</div>
					<div class="row">
						<div class="six columns {% if form.acfe_membership.errors %}error{% endif %}">
							{{ form.acfe_membership.label_tag }}
							{{ form.acfe_membership }}
							{% for errors in form.acfe_membership.errors %}
							<small>{{ errors|escape }}</small>
							{% endfor %}
							<p>
								<a href="http://www.acfe.com/" target="_blank">http://www.acfe.com/</a>
							</p>
						</div>
					</div>
				</fieldset>
				<div class="row">
					<div class="six columns {% if form.resume.errors %}error{% endif %}" id="resume">
						{{ form.resume.label_tag }}
						{{ form.resume }}
						{% for errors in form.resume.errors %}
						<small>{{ errors|escape }}</small>
						{% endfor %}
						<p>
							{{ form.resume.help_text }}
						</p>
					</div>
				</div>
				<hr>
				<a class="secondary button" href="{% url dashboard_view %}">Cancel</a>
				<input type="submit" value="Submit" class="button"/>
			</form>
		</div>
	</div>
</div>
{% endblock base_content %}

utdallasiia/apps/resumebook/templates/resumebook/resume_list.html
{% extends "base.html" %}
{% load sekizai_tags %}

{% block base_content %}
{% addtoblock "css" %}
<link rel="stylesheet" href="{{ STATIC_URL }}stylesheets/responsive-tables.css">
{% endaddtoblock %}

<div class="row">
	<div class="twelve columns">
		<h3>Resume Book</h3>
		<hr>
		{% if resume_list %}
		<p>
			The resume book requires <a href="http://get.adobe.com/reader/" target="_blank">Acrobat Reader</a> to view.
		</p>
		<table class="twelve responsive" id="resumebook">
			<thead>
				<tr>
					<th data-sort="string"><a href="#">Last Name</a></th>
					<th data-sort="string"><a href="#">First Name</a></th>
					<th data-sort="string"><a href="#">Grad Month</a></th>
					<th data-sort="int"><a href="#">Grad Year</a></th>
					<th data-sort="string"><a href="#">Degree Plan(s)</a></th>
					<th data-sort="string"><a href="#">US Citizen/PR</a></th>
					<th data-sort="string"><a href="#">Position</a></th>
					<th data-sort="string"><a href="#">Travel</a></th>
					<th data-sort="string"><a href="#">Relocate?</a></th>
					<th data-sort="string"><a href="#">IA Course</a></th>
					<th data-sort="string"><a href="#">IT Position</a></th>
				</tr>
			</thead>
			<tbody>
				{% for resume in resume_list %}
				<tr>
					<td><a href="{% url download_resume resume.pk %}">{{ resume.user.last_name }}</a></td>
					<td>{{ resume.user.first_name }}</td>
					<td>{{ resume.user.memberprofile.graduation_month }}</td>
					<td>{{ resume.user.memberprofile.graduation_year }}</td>
					<td>{{ resume.user.memberprofile.degree_plans.all|join:", " }}</td>
					<td>{{ resume.user.memberprofile.get_citizen_resident_display }}</td>
					<td>{{ resume.get_position_display }}</td>
					<td>{{ resume.get_travel_display }}</td>
					<td>{{ resume.get_relocate_display }}</td>
					<td>{{ resume.get_ia_course_display }}</td>
					<td>{{ resume.get_it_position_display }}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
		{% else %}
		<p>
			There are no resume currently in the resume book.
		</p>
		{% endif %}
	</div>
</div>

{% addtoblock "js" %}
<script src="{{ STATIC_URL }}javascripts/zurb-responsive-tables/responsive-tables.js"></script>
<script src="{{ STATIC_URL }}javascripts/stupidtable/stupidtable.min.js"></script>
<script type="text/javascript">
	var table = $("#resumebook").stupidtable();
	table.bind('aftertablesort', function(event, data) {
		// data.column - the index of the column sorted after a click
		// data.direction - the sorting direction (either asc or desc)

		var th = $(this).find("th");
		th.find(".arrow").remove();
		var arrow = data.direction === "asc" ? "↑" : "↓";
		th.eq(data.column).append('<span class="arrow">' + arrow + '</span>');
	}); 
</script>
{% endaddtoblock %}
{% endblock base_content %}