utdallasiia/apps/jobpostings/urls.py
from django.conf.urls import patterns, include, url
from utdallasiia.apps.jobpostings.views import JobPostingView, JobPostingDetail, JobPostingUserView, CreateJobPosting, UpdateJobPosting, CloseJobPosting, DeleteJobPosting

urlpatterns = patterns('',
    url(r'^$', JobPostingView.as_view(), name='job_posting_view'),
    url(r'^(?P<pk>\d+)/$', JobPostingDetail.as_view(), name='job_posting_detail'),
    url(r'^user/$', JobPostingUserView.as_view(), name='job_posting_user_view'),
    url(r'^user/new/$', CreateJobPosting.as_view(), name='create_job_posting'),
    url(r'^user/(?P<pk>\d+)/$', UpdateJobPosting.as_view(), name='update_job_posting'),
    url(r'^user/(?P<pk>\d+)/close/$', CloseJobPosting.as_view(), name='close_job_posting'),
    url(r'^user/(?P<pk>\d+)/delete/$', DeleteJobPosting.as_view(), name='delete_job_posting'),
)

utdallasiia/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic.simple import redirect_to
from django.views.generic.base import TemplateView

admin.autodiscover()

urlpatterns = patterns('',
    # Setup LinkedIn login/logout urls
    url(r'', include('social_auth.urls')),
    url(r'^login/$', TemplateView.as_view(template_name='login.html'), name='auth_login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='auth_logout'),
    
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    # Setup Paypal IPN
    url(settings.PAYPAL_IPN_URL, include('paypal.standard.ipn.urls')),
    
    # Django Blog Zinnia
    url(r'^blog/', include('zinnia.urls')),
    url(r'^comments/', include('django.contrib.comments.urls')),
    
    # Finally, load Django CMS urls
    url(r'^', include('cms.urls')),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.SMEDIA_URL, document_root=settings.SMEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

utdallasiia/apps/jobpostings/models.py
from django.contrib.auth.models import User
from django.db import models
from django_localflavor_us.models import USStateField

class JobPosting(models.Model):
    TYPE_CHOICES = (
        ('FT', 'Full-time'),
        ('PT', 'Part-time'),
        ('IN', 'Internship'),
    )
    
    PENDING_STATUS = 0
    OPEN_STATUS = 1
    CLOSED_STATUS = 2
    STATUS_CHOICES = (
        (PENDING_STATUS, 'Pending'),
        (OPEN_STATUS, 'Open'),
        (CLOSED_STATUS, 'Closed'),
    )
    
    user = models.ForeignKey(User)
    job_title = models.CharField(max_length=30)
    company = models.CharField(max_length=30)
    city = models.CharField(max_length=35)
    state = USStateField()
    type = models.CharField(max_length=2, choices=TYPE_CHOICES)
    job_description = models.TextField()
    skill_experience = models.TextField()
    company_description = models.TextField()
    status = models.IntegerField(choices=STATUS_CHOICES, default=PENDING_STATUS)
    
    job_title.help_text = 'e.g. Internal Auditor I'
    job_description.help_text = 'Include a brief job description, approximate start date, and a link or email to apply for the position.'    
    skill_experience.verbose_name = 'Desired skills and experience'
    
    def __unicode__(self):
        return self.job_title

utdallasiia/apps/jobpostings/forms.py
from django import forms
from utdallasiia.apps.jobpostings.models import JobPosting

class JobPostingForm(forms.ModelForm):
    class Meta:
        model = JobPosting
        exclude = (
            'user',
            'status',
        )

utdallasiia/apps/jobpostings/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import redirect, render
from django.utils.decorators import method_decorator
from django.views.generic.detail import BaseDetailView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from utdallasiia.apps.jobpostings.forms import JobPostingForm
from utdallasiia.apps.jobpostings.models import JobPosting

class JobPostingView(ListView):
    queryset = JobPosting.objects.exclude(status=JobPosting.PENDING_STATUS).order_by('job_title')

class JobPostingDetail(DetailView):
    model = JobPosting
    raise_exception = False
    
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        has_permission = request.user.memberprofile.is_employer or request.user.memberprofile.is_paid
        
        if not has_permission:  # If the user lacks the permission
            if self.raise_exception:  # *and* if an exception was desired
                raise PermissionDenied  # return a forbidden response.
            else:
                return render(request, 'jobpostings/jobposting_access.html')
            
        return super(JobPostingDetail, self).dispatch(request, *args, **kwargs)

class JobPostingUserView(ListView):
    raise_exception = True
    
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        has_permission = request.user.memberprofile.is_employer
        
        if not has_permission:  # If the user lacks the permission
            if self.raise_exception:  # *and* if an exception was desired
                raise PermissionDenied  # return a forbidden response.
            
        return super(JobPostingUserView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return JobPosting.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super(JobPostingUserView, self).get_context_data(**kwargs)
        context['user_view'] = True
        return context

class CreateJobPosting(CreateView):
    form_class = JobPostingForm
    template_name = 'jobpostings/jobposting_form.html'
    success_url = reverse_lazy('job_posting_user_view')
    raise_exception = True
    
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        has_permission = request.user.memberprofile.is_employer
        
        if not has_permission:  # If the user lacks the permission
            if self.raise_exception:  # *and* if an exception was desired
                raise PermissionDenied  # return a forbidden response.

        return super(CreateJobPosting, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        jobposting = form.save(commit=False)
        jobposting.user = self.request.user
        jobposting.save()
        return super(CreateJobPosting, self).form_valid(form)

class UpdateJobPosting(UpdateView):
    form_class = JobPostingForm
    template_name = 'jobpostings/jobposting_form.html'
    success_url = reverse_lazy('job_posting_user_view')
    raise_exception = True
    
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        has_permission = request.user.memberprofile.is_employer
        
        if not has_permission:  # If the user lacks the permission
            if self.raise_exception:  # *and* if an exception was desired
                raise PermissionDenied  # return a forbidden response.

        return super(UpdateJobPosting, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(UpdateJobPosting, self).get_context_data(**kwargs)
        context['update_view'] = True
        return context
    
    def get_queryset(self):
        return JobPosting.objects.filter(user=self.request.user)
    
    def form_valid(self, form):
        jobposting = form.save(commit=False)
        jobposting.status = JobPosting.PENDING_STATUS
        jobposting.save()
        return super(UpdateJobPosting, self).form_valid(form)

class CloseJobPosting(BaseDetailView):
    raise_exception = True

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        has_permission = request.user.memberprofile.is_employer
        
        if not has_permission:  # If the user lacks the permission
            if self.raise_exception:  # *and* if an exception was desired
                raise PermissionDenied  # return a forbidden response.

        return super(CloseJobPosting, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return JobPosting.objects.filter(user=self.request.user)

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.status = JobPosting.CLOSED_STATUS
        self.object.save()
        return redirect('job_posting_user_view')

class DeleteJobPosting(DeleteView):
    success_url = reverse_lazy('job_posting_user_view')
    raise_exception = True
    
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        has_permission = request.user.memberprofile.is_employer
        
        if not has_permission:  # If the user lacks the permission
            if self.raise_exception:  # *and* if an exception was desired
                raise PermissionDenied  # return a forbidden response.

        return super(DeleteJobPosting, self).dispatch(request, *args, **kwargs)
    
    def get_queryset(self):
        return JobPosting.objects.filter(user=self.request.user)

utdallasiia/apps/jobpostings/templates/jobpostings/jobposting_access.html
{% extends "base.html" %}

{% block base_content %}
<div class="row">
	<div class="six columns centered">
		<div class="panel radius">
			<h3>Membership Required</h3>
			<hr>
			<h5 class="subheader">You must be an employer or a paid member in order to view job posting details.</h5>
			<a class="button" href="{% url dashboard_view %}">My Account &raquo;</a>
			<hr>
		</div>
	</div>
</div>
{% endblock base_content %}

utdallasiia/apps/jobpostings/templates/jobpostings/jobposting_confirm_delete.html
{% extends "base.html" %}

{% block base_content %}
<div class="row">
	<div class="six columns centered">
		<div class="panel radius">
			<h3>Delete Job Posting</h3>
			<hr>
			<h5 class="subheader">Are you sure you want to delete the job posting for "{{ jobposting.job_title }}"?</h5>
			<div class="row">
				<div class="twelve columns">
					<form action="{% url delete_job_posting jobposting.pk %}" method="post">
						{% csrf_token %}
						<a class="secondary button" href="{% url update_job_posting jobposting.pk %}">Cancel</a>
						<input type="submit" value="Yes, I'm sure" class="button"/>
					</form>
				</div>
			</div>
			<hr>
		</div>
	</div>
</div>
{% endblock base_content %}

utdallasiia/apps/jobpostings/templates/jobpostings/jobposting_detail.html
{% extends "base.html" %}

{% block base_content %}
<div class="row">
	<div class="twelve columns">
		<h3>Job Postings</h3>
		<hr>
		<h5>{{ jobposting.job_title }}</h5>
		<h6>{{ jobposting.company }} - {{ jobposting.city }}, {{ jobposting.state }}
		<p>
			{% if jobposting.status == 0 %}
			<span class="label">Pending</span>
			{% elif jobposting.status == 1 %}
			<span class="success label">Open</span>
			{% elif jobposting.status == 2 %}
			<span class="alert label">Closed</span>
			{% endif %}

			<span class="label">{{ jobposting.get_type_display }}</span>
		</p>
		<h6>Job description:</h6>
		<p>{{ jobposting.job_description|linebreaksbr }}</p>
		<h6>Desired skills and experience:</h6>
		<p>{{ jobposting.skill_experience|linebreaksbr }}</p>
		<h6>Company description:</h6>
		<p>{{ jobposting.company_description|linebreaksbr }}</p>
		<hr>
		<p>
			<a class="secondary button" href="{% url job_posting_view %}">&laquo; Back</a>
		</p>
	</div>
</div>
{% endblock base_content %}

utdallasiia/apps/jobpostings/templates/jobpostings/jobposting_form.html
{% extends "base.html" %}

{% block base_content %}
<div class="row">
	<div class="twelve columns">
		<h3>Edit Job Posting</h3>
		<hr>
		<div class="eight columns end">
			<form method="post" action="" class="custom">
				{% csrf_token %}
				<div class="row">
					<div class="six columns {% if form.job_title.errors %}error{% endif %}">
						{{ form.job_title.label_tag }}
						{{ form.job_title }}
						{% for errors in form.job_title.errors %}
						<small>{{ errors|escape }}</small>
						{% endfor %}
						<p>
							{{ form.job_title.help_text }}
						</p>
					</div>
					<div class="six columns {% if form.type.errors %}error{% endif %}">
						{{ form.type.label_tag }}
						{{ form.type }}
						{% for errors in form.type.errors %}
						<small>{{ errors|escape }}</small>
						{% endfor %}
						<p>
							{{ form.type.help_text }}
						</p>
					</div>
				</div>
				<div class="row">
					<div class="six columns {% if form.company.errors %}error{% endif %}">
						{{ form.company.label_tag }}
						{{ form.company }}
						{% for errors in form.company.errors %}
						<small>{{ errors|escape }}</small>
						{% endfor %}
						<p>
							{{ form.company.help_text }}
						</p>
					</div>
				</div>
				<div class="row">
					<div class="six columns {% if form.city.errors %}error{% endif %}">
						{{ form.city.label_tag }}
						{{ form.city }}
						{% for errors in form.city.errors %}
						<small>{{ errors|escape }}</small>
						{% endfor %}
						<p>
							{{ form.city.help_text }}
						</p>
					</div>
					<div class="six columns {% if form.state.errors %}error{% endif %}">
						{{ form.state.label_tag }}
						{{ form.state }}
						{% for errors in form.state.errors %}
						<small>{{ errors|escape }}</small>
						{% endfor %}
						<p>
							{{ form.state.help_text }}
						</p>
					</div>
				</div>
				<div class="row">
					<div class="twelve columns {% if form.job_description.errors %}error{% endif %}">
						{{ form.job_description.label_tag }}
						<p>
							{{ form.job_description.help_text }}
						</p>
						{{ form.job_description }}
						{% for errors in form.job_description.errors %}
						<small>{{ errors|escape }}</small>
						{% endfor %}
					</div>
					<div class="twelve columns {% if form.skill_experience.errors %}error{% endif %}">
						{{ form.skill_experience.label_tag }}
						<p>
							{{ form.skill_experience.help_text }}
						</p>
						{{ form.skill_experience }}
						{% for errors in form.skill_experience.errors %}
						<small>{{ errors|escape }}</small>
						{% endfor %}
					</div>
					<div class="twelve columns {% if form.company_description.errors %}error{% endif %}">
						{{ form.company_description.label_tag }}
						<p>
							{{ form.company_description.help_text }}
						</p>
						{{ form.company_description }}
						{% for errors in form.company_description.errors %}
						<small>{{ errors|escape }}</small>
						{% endfor %}
					</div>
				</div>
				<hr>
				<a class="secondary button" href="{% url job_posting_user_view %}">Cancel</a>
				<input type="submit" value="Submit" class="button"/>
				{% if update_view %}
				<div class="right">
					<a class="button" href="{% url close_job_posting jobposting.pk %}">Close Job</a>
					<a class="alert button" href="{% url delete_job_posting jobposting.pk %}">Delete</a>
				</div>
				{% endif %}
			</form>
		</div>
	</div>
</div>
{% endblock base_content %}

utdallasiia/apps/jobpostings/templates/jobpostings/jobposting_list.html
{% extends "base.html" %}
{% load sekizai_tags %}

{% block base_content %}
{% addtoblock "css" %}
<link rel="stylesheet" href="{{ STATIC_URL }}stylesheets/responsive-tables.css">
{% endaddtoblock %}

<div class="row">
	<div class="twelve columns">
		<h3>{% if user_view %}My {% endif %}Job Postings</h3>
		<hr>
		{% if jobposting_list %}
		<table class="twelve responsive" id="jobpostings">
			<thead>
				<tr>
					<th data-sort="string"><a href="#">Job Title</a></th>
					<th data-sort="string"><a href="#">Company</a></th>
					<th data-sort="string"><a href="#">City</a></th>
					<th data-sort="string"><a href="#">State</a></th>
					<th data-sort="string"><a href="#">Type</a></th>
					<th data-sort="string"><a href="#">Status</a></th>
				</tr>
			</thead>
			<tbody>
				{% for jobposting in jobposting_list %}
				<tr>
					{% if user_view %}
					<td><a href="{% url update_job_posting jobposting.pk %}">{{ jobposting.job_title }}</a></td>
					{% else %}
					<td><a href="{% url job_posting_detail jobposting.pk %}">{{ jobposting.job_title }}</a></td>
					{% endif %}
					<td>{{ jobposting.company }}</td>
					<td>{{ jobposting.city }}</td>
					<td>{{ jobposting.state }}</td>
					<td>{{ jobposting.get_type_display }}</td>
					<td>{{ jobposting.get_status_display }}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
		{% else %}
		<p>
			There are currently no job postings.
		</p>
		{% endif %}
		{% if user_view %}
		<a class="secondary button" href="{% url dashboard_view %}">Back to My Account</a>
		<a class="button" href="{% url create_job_posting %}">Create new job posting &raquo;</a>
		{% endif %}
	</div>
</div>

{% addtoblock "js" %}
<script src="{{ STATIC_URL }}javascripts/zurb-responsive-tables/responsive-tables.js"></script>
<script src="{{ STATIC_URL }}javascripts/stupidtable/stupidtable.min.js"></script>
<script type="text/javascript">
	var table = $("#jobpostings").stupidtable();
	table.bind('aftertablesort', function(event, data) {
		// data.column - the index of the column sorted after a click
		// data.direction - the sorting direction (either asc or desc)

		var th = $(this).find("th");
		th.find(".arrow").remove();
		var arrow = data.direction === "asc" ? "↑" : "↓";
		th.eq(data.column).append('<span class="arrow">' + arrow + '</span>');
	}); 
</script>
{% endaddtoblock %}
{% endblock base_content %}